# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maindisplay.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5.QtWidgets import *
from PyQt5 import uic
from PyQt5 import QtCore
from GuestUI import Form
from Host import Form1


form_main = uic.loadUiType("maindisplay.ui")[0]

class MainWindow(QMainWindow,QWidget, form_main):
    def __init__(self):
        super().__init__()
        self.initUI()
        self.show()

    def initUI(self):
        self.setupUi(self)
        self.btnGuest.clicked.connect(self.move_to_guest)
        self.btnHost.clicked.connect(self.move_to_host)


    def move_to_guest(self):
        self.close()#hide main window
        self.second = Form()
        self.second.exec()
        self.show()

    def move_to_host(self):
        self.close()
        self.third = Form1()
        self.third.exec()
        self.show()
        
if __name__ == "__main__":
    app = QApplication(sys.argv)
    win = MainWindow()
    sys.exit(app.exec_())
 